### ISSUE TITLE
add me on discord ò-ò

### ISSUE THREAD

**Issue by Shiberal** [Mrcubix/BO2-GSC-Documentation#1]
ò-ò could you explain me how to dump stuff?

**Comment by Mrcubix** [comment]
For BO2 specifically, you need to make use of [t6-gsc-utils](https://github.com/fedddddd/t6-gsc-utils).
It has multiple functions to serialize all kind of variables.

There is although an issue with it, any recursive structures will be replaced with `[[ reference xxxx ]]`.
This is a terrible way to handle it and they don't care, so you'll have to make your own serializer.

This serializer will involve iterating over an array, a struct or an entity's children.
Those types of course requires different methods to get the children out of them.
Those can be found in the documentation provided there.

Finally, for info, i'm not working on releasing anything related to Plutonium publicly anymore.
Partly due to the discord's staff not being able to take the truth an criticism in and just abusing their power instead.
(And i won't talk about rekt's god complex)
Therefore, If you need more information, you'll have to work you way to find it yourself, Sorry.
